language: node_js
node_js:
  - "0.10"
  - "0.8"
  - "0.6"
before_script: "npm install mocha"
notifications:
  email:
    recipients:
      - vidyac.raghav@gmail.com
        on_success:always
        on_failure:always
  campfire: [qhode1]:[99b2845783c6adf698c143927e45d11045c47804 ]@[572545]

